### PR TITLE
Use New Relic's V2 API for marking deploys

### LINKED ISSUE #141: New Relic API v2
Currently the New Relic example is using New Relic's v1 API. Seems that doesn't work anymore. Has anyone had success with v2?

### PR DESCRIPTION
**Pull request by sarahg**
Closes #141 and #155

PR includes the following changes:

- Use the New Relic v2 API (inspired largely by @pingevt in [this issue comment](https://github.com/pantheon-systems/quicksilver-examples/issues/141)).
- Use PHP cURL so we can capture more debugging output and set timeouts.

### CODE REVIEW

**Comment by davidneedham** [comment]
I just added this to a WordPress site and it worked flawlessly.

File: new_relic_deploy/new_relic_deploy.php [hunk 1]
```diff
@@ -47,29 +46,108 @@
...
 }
 elseif ($_POST['wf_type'] == 'deploy') {
-  // Topline description:
   $description = 'Deploy to environment triggered via Pantheon';
-  // Find out if there's a deploy tag:
-  $revision = `git describe --tags --abbrev=0`;
-  // Get the annotation:
-  $changelog = `git tag -l -n99 $revision`;
+  // Check if there's a deploy tag.
+  $revision = `git describe --tags`;
```
Comment (joeparsons) [inline new_relic_deploy/new_relic_deploy.php]:
```suggestion
  $revision = `git describe --tags --abbrev=0`;
```

**Review by philoSurfer — APPROVED** [review]
this has been waiting for approval for some time and V2 api needs to be supported in our examples moving forward.
